### ISSUE TITLE
[FIX] 팀 참가 request 및 response 변경

### ISSUE THREAD

**Issue by leedabin2** [cubeTalk/cubeTalk-BE#13]
## 💡 Feature Issue

request
Null Empty 값이 아닌 불필요한 필드에 대해서 포함하지 않도록 변경
response
서버의 시간을 전송하여 참가 시각을 저장하도록 추가

## 🌿  To-do

- [ ] chatRoomService joinChatRoom 변경
- [ ] response DTO 수정
- [ ] request DTO 수정
