### ISSUE TITLE
[FEAT] 채팅방 내 개요 수정 & home 버튼 GET 요청처리

### ISSUE THREAD

**Issue by leedabin2** [cubeTalk/cubeTalk-BE#19]
## 💡 Feature Issue

채팅방 내 개요를 수정후 db를 업데이트합니다.
GET 요청시 데이터를 전송합니다.

## 🌿  To-do

- [ ] 해당 swagger API 작성
- [ ]  /chat/{id}/description PATCH 구현
- [ ] /chat/{id}/home GET 구현
