### ISSUE TITLE
[FEAT] spring + mongoDB docker-compose 설정

### ISSUE THREAD

**Issue by leedabin2** [cubeTalk/cubeTalk-BE#2]
## 💡 Feature Issue

docker-compose를 활용하여 spring boot + mongoDB 를 설정

## 🌿  To-do

- [ ] Dockerfile 생성 
- [ ] docker-compose.yml
- [ ] application.yml - mongoDB 연동
- [ ] docker 이미지화
- [ ] .env 파일로 환경변수 관리
