### ISSUE TITLE
[FIX] 채팅방 참가시 Participants 에 nickName 추가 및 중복검사 해당 채팅방에서만 제한 & response 채팅방 정보들 포함

### ISSUE THREAD

**Issue by leedabin2** [cubeTalk/cubeTalk-BE#32]
## 💡 Feature Issue

채팅방 참가시 Participants 에 nickName 추가 및 중복검사 해당 채팅방에서만 제한 & response 채팅방 정보들 포함
## 🌿  To-do

- [x] 채팅방 참가 시 participants 엔티티에 nickName 필드 추가
- [x] nickName 중복검사 시 전체 채팅방 검사 -> 해당 채팅방으로 제한
- [x] response에 채팅방 정보들을 추가 전송
